import fs from 'node:fs';
import crypto from 'node:crypto';
const BASE='https://magi-bridge-v4.vercel.app/api/step';
const FX=160, CAP_YEN=120; let spentUsd=0; const dir='/tmp/pkg1';
const expected={
 'T009R_checker_C_v3_1_candidate.py':'c7aac7e6c5d31f3710849a1c20ec76bbe7364356ee45d027b6fce5c93a3d9f64',
 'T009R_Confirmatory_Prereg_DRAFT_v0.6_preanchor.json':'139ef218362dc121e72cacf57ea87b2abcda6f5754f5adf0e0211cc7f48c2afd',
 'T009R_expected_manifest_selfcheck_v1.py':'d09fc155384ee3aee842c19e19a27fbc882635aaea59bf870cb35ac3899d5d29',
 'T009R_checker_C_v3_selftest_stdout.txt':'69c2542b79f9bae05e1fc08c9ea860f5250527cc4beb1762d214a78af1c40980',
 'T009R_v3_1_bridge_context.json':'c7c6b6908331c233c2a5ada598d82151777dec1bfb3322581b67c3725ff046ea'
};
const sha=s=>crypto.createHash('sha256').update(s,'utf8').digest('hex'); const raw={};
for(const [name,want] of Object.entries(expected)){const content=fs.readFileSync(`${dir}/${name}`,'utf8');const got=sha(content);if(got!==want)throw new Error(`EVIDENCE_HASH_MISMATCH ${name} ${got}`);raw[name]=content;}
const evidence=[
 {name:'T009R_checker_C_v3_1_candidate.txt',type:'text/plain',content:raw['T009R_checker_C_v3_1_candidate.py']},
 {name:'T009R_Confirmatory_Prereg_DRAFT_v0.6_preanchor.json',type:'application/json',content:raw['T009R_Confirmatory_Prereg_DRAFT_v0.6_preanchor.json']},
 {name:'T009R_expected_manifest_selfcheck_v1.txt',type:'text/plain',content:raw['T009R_expected_manifest_selfcheck_v1.py']},
 {name:'T009R_checker_C_v3_baseline_18_selftest_stdout.txt',type:'text/plain',content:raw['T009R_checker_C_v3_selftest_stdout.txt']},
 {name:'T009R_v3_1_bridge_context.json',type:'application/json',content:raw['T009R_v3_1_bridge_context.json']}
].map(e=>({...e,size:Buffer.byteLength(e.content),client_sha256:sha(e.content)}));
const totalChars=evidence.reduce((a,e)=>a+e.content.length,0); if(evidence.length>5)throw new Error('EVIDENCE_COUNT'); if(totalChars>80000)throw new Error(`EVIDENCE_TOO_LARGE ${totalChars}`);
const topic=`T009R Checker C v3.1 targeted independent code re-audit. Previous v3 code-level PASS is not a LOCK approval. Audit the supplied exact v3.1 code SHA c7aac7e6...d9f64 and prereg v0.6 PREANCHOR SHA 139ef218...c2afd. The actual prospective expected pre-outcome manifest does not yet exist/finalize, so v0.6 preanchor SHA is NOT a final prereg/LOCK hash and trial LOCK remains prohibited. A/B implementation has NOT started and must not start until manifest anchor and independence contract are finalized. Verify from code/prereg: (1) removing machine_reconciliation.partition_set now fails closed rather than silently defaulting to BASELINE; (2) null inference.invalid_bootstrap_replicate_policy and machine_reconciliation.float_comparison are malformed prereg inputs yielding PROTOCOL_INVALID/exit2 path rather than checker internal exception; (3) expected manifest self-consistency is validated before bundles, including FULL=A+B for race_count, primary_subgroup_rows, distinct_race_dates, total dates, and standalone selfcheck matches that intent; (4) invalid n/wins state is INVALID and valid zero-event remains INCONCLUSIVE_ZERO_EVENTS; (5) prereg explicitly defines A/B shared-allowed/shared-forbidden artifacts and states Checker C cannot verify common upstream defects or probability correctness; (6) SUSPECT_NON_INDEPENDENT_EXECUTION remains diagnostic-only for scientific verdict but automatically blocks promotion/LOCK and requires human review; (7) checker-prereg coupling is explicit and any contract change requires paired checker version bump/re-audit. Confirm no scientific threshold, subgroup, endpoint, Gate or SUPPORTED condition was relaxed. Local regression reports 25/25 PASS (old 18 + seven targeted cases) and manifest selfcheck 5/5; treat these as supplied evidence, not as a substitute for code review. Final verdict scope must be Checker C v3.1 + v0.6 governance hardening only. Even PASS must explicitly preserve LOCK prohibition and actual-manifest/A-B blockers.`;
async function step(payload){const remaining=Math.max(0,CAP_YEN-spentUsd*FX);if(remaining<=0)throw new Error('BUDGET_CAP');const r=await fetch(BASE,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,budget_remaining_yen:remaining,budget_fx_yen_per_usd:FX})});const t=await r.text();let d;try{d=JSON.parse(t)}catch{throw new Error(`NON_JSON_${r.status}:${t.slice(0,300)}`)}if(!r.ok)throw new Error(d.error||`HTTP_${r.status}`);if(d.usage?.usd!=null)spentUsd+=Number(d.usage.usd||0);return d}
const transcript=[];const push=d=>transcript.push({stage:d.stage,speaker:d.speaker,model:d.model,text:d.text,structured:d.structured||null,usage:d.usage||null,evidence:d.evidence||null});
try{let g=await step({stage:'gpt_initial',topic,evidence});push(g);let a=await step({stage:'claude_audit',topic,previous:g.text,evidence});push(a);g=await step({stage:'gpt_revise',topic,previous:g.text,audit:a.text,evidence});push(g);let v=await step({stage:'claude_verdict',topic,previous:g.text,evidence});push(v);const out={run_kind:'T009R_CHECKER_C_V3_1_TARGETED_REAUDIT',production_url:BASE,evidence:evidence.map(e=>({name:e.name,sha256:e.client_sha256,chars:e.content.length})),evidence_total_chars:totalChars,spent_usd:spentUsd,spent_yen:spentUsd*FX,final_structured:v?.structured||null,transcript,completed_at:new Date().toISOString()};fs.writeFileSync('bridge_followup_result.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}catch(err){const out={run_kind:'T009R_CHECKER_C_V3_1_TARGETED_REAUDIT',error:String(err?.stack||err),spent_usd:spentUsd,spent_yen:spentUsd*FX,transcript,completed_at:new Date().toISOString()};fs.writeFileSync('bridge_followup_result.json',JSON.stringify(out,null,2));console.error(JSON.stringify(out,null,2));process.exit(1)}
